// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 7);
user_pref("app.normandy.user_id", "5be6afa0-34d7-4cff-86ea-cf042099c041");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575133320);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 5098);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575133289);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4504f383-1a6b-486b-b5dc-5fd573e9b9b1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575133313422");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575135093422");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575133292592");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575136892592");
user_pref("browser.search.region", "SG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191031062442");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575134345");
user_pref("browser.slowStartup.averageTime", 572);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20191031062442");
user_pref("browser.startup.homepage_override.mstone", "70.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1575134345);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575133291661");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "70.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "6fcb1079f6824e05a295aa42bbb09b42");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191031062442");
user_pref("extensions.lastAppVersion", "70.0.1");
user_pref("extensions.lastPlatformVersion", "70.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e7556e2e-c250-47ce-8938-c770a28b3d8c\",\"screenshots@mozilla.org\":\"5c8255b8-7c3f-4d45-8b1c-7fd3071693b0\",\"webcompat-reporter@mozilla.org\":\"e8ab3774-beb2-4500-ac0f-c1401da88f2a\",\"webcompat@mozilla.org\":\"d59675e7-0a59-4aba-bee7-fa42e41a4bd7\",\"default-theme@mozilla.org\":\"dd6f9253-d4fc-4a2e-af8b-90a504453dc8\",\"google@search.mozilla.org\":\"98aa948e-ee1a-422b-82de-dbef99d1b7d6\",\"amazondotcom@search.mozilla.org\":\"a4784b16-6b3a-4fc8-a5bb-145923845081\",\"bing@search.mozilla.org\":\"972103ad-d3a8-487f-94bd-faa458552f4a\",\"ddg@search.mozilla.org\":\"461b6fdd-0302-4ec9-95de-575b89ee2550\",\"ebay@search.mozilla.org\":\"ebeae18e-28f6-40be-8555-ded8e8875040\",\"twitter@search.mozilla.org\":\"35ac4cd0-2aee-4049-9ec5-c18b423e42a4\",\"wikipedia@search.mozilla.org\":\"b4f173db-86c2-490d-80b3-6475c2af9b60\",\"https-everywhere@eff.org\":\"d3ec9dbb-f6d1-45e3-b157-2d3d7d476ce7\",\"jid1-MnnxcxisBPnSXQ@jetpack\":\"5b62829c-05d2-4206-a17e-22aed6acd2fb\",\"jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack\":\"8aa380cc-259d-4a74-bc33-74d022cefc96\",\"jid1-BoFifL9Vbdl2zQ@jetpack\":\"510f94e0-33aa-45a4-a1be-547d4f6f6d78\",\"CookieAutoDelete@kennydo.com\":\"53dc6298-2ec1-48ab-a512-01417897e465\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "6ed3163c-1050-49b1-9392-3f748a01234a");
user_pref("security.sandbox.plugin.tempDirSuffix", "4a9af8d8-df13-470a-bcdf-98d83513a274");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1575134344);
user_pref("toolkit.telemetry.cachedClientID", "0c0cd0d4-5078-40d8-a2f6-c8668b8a88ca");
user_pref("toolkit.telemetry.previousBuildID", "20191031062442");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "holdback");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
