// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "08db8a94-45ea-41b4-b136-b90d1c80c34e");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1172);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1565273417);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{199a2e88-57d7-4a05-89bc-b71cc0b0e91d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1565273410101");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1565275215101");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1565273393931");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1565276993931");
user_pref("browser.search.region", "SG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190718161435");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.slowStartup.averageTime", 1008);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1565273418);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1565273392674");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "26233a881c574149a81584013bb61ecf");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190718161435");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"188bbd99-61a6-4486-88b3-6e53a01648fb\",\"fxmonitor@mozilla.org\":\"0d7b6c0b-f94e-489a-bb2e-9cba186e08ea\",\"screenshots@mozilla.org\":\"2e0354c4-42e3-4b23-b046-7671f205ace8\",\"webcompat-reporter@mozilla.org\":\"7032e428-c894-4e97-9d57-6355a28d2633\",\"webcompat@mozilla.org\":\"0b473194-096c-4064-a4c2-7a09bb95cd00\",\"default-theme@mozilla.org\":\"0e2f6092-221b-42b0-b20f-c639b90443f3\",\"google@search.mozilla.org\":\"05d2e496-7315-45ab-b13d-949242d87854\",\"amazondotcom@search.mozilla.org\":\"4bbaa035-b0d7-4506-8fbf-c6288a66cf2b\",\"bing@search.mozilla.org\":\"f98de0ef-9c64-4c2f-a6a2-26ae729bd795\",\"ddg@search.mozilla.org\":\"9c8aa187-3bb7-41ca-850c-d6773dece5dc\",\"ebay@search.mozilla.org\":\"5b54337f-8b58-4ca9-ab56-737a07733e12\",\"twitter@search.mozilla.org\":\"20a32a5c-d645-4686-abf6-b57c5305e4cc\",\"wikipedia@search.mozilla.org\":\"33cb977a-5dd8-4b19-aaa2-ea738768e44b\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2abfa062-97b4-4097-ac69-f2898ba37f43");
user_pref("security.sandbox.plugin.tempDirSuffix", "1f7ad212-c6d5-414e-8276-225fe24fd009");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1565273417);
user_pref("toolkit.telemetry.cachedClientID", "b9195a9c-6b22-493f-9425-34070e4fb3bd");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
