// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "b4347f03-6bf1-40e4-99a2-185d89134ce8");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1565273500);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2216);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{949bfed5-b1b4-425a-8170-70ae203a8119}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1565273509955");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1565275312955");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1565273474063");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1565277074063");
user_pref("browser.search.region", "SG");
user_pref("browser.slowStartup.averageTime", 1402);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.lastColdStartupCheck", 1565273471);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1565273472289");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "b7474db37ebb4050900dfaca1034a193");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4acfeda9-4e85-4a87-8833-8c711c553eaa\",\"fxmonitor@mozilla.org\":\"b7b68d87-980c-4233-be46-79943e8b6f61\",\"screenshots@mozilla.org\":\"07538074-11b9-41b5-bb17-faffef4387c7\",\"webcompat-reporter@mozilla.org\":\"a9f06411-e90c-4935-bcb4-2ef2544d35b4\",\"webcompat@mozilla.org\":\"89c5113b-e5ee-47c9-b840-1ac77f6faa7e\",\"default-theme@mozilla.org\":\"f6d92459-2ea8-4260-9e41-6733ed826486\",\"google@search.mozilla.org\":\"b7824b9c-74c5-4df0-83cb-14c1fb33c784\",\"amazondotcom@search.mozilla.org\":\"a8f14929-96cb-48f6-93f5-2dde35a61c93\",\"bing@search.mozilla.org\":\"ad0da675-e857-468d-b6ad-35f63a7a625e\",\"ddg@search.mozilla.org\":\"682eb6da-5fcc-4c0a-982f-4207c041fb1f\",\"ebay@search.mozilla.org\":\"3bdf5608-6c83-4715-bd0d-69db949e836b\",\"twitter@search.mozilla.org\":\"1df3ebdf-98fb-4329-abf4-05de73a96dcb\",\"wikipedia@search.mozilla.org\":\"fa84d12e-3570-46dc-98f5-8d386fe8dabb\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8a4bcea9-5547-40a1-8b94-a1f8114cb452");
user_pref("security.sandbox.plugin.tempDirSuffix", "4ddac1d3-795d-48db-aa9c-89538d77405a");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1565273469);
user_pref("toolkit.telemetry.cachedClientID", "b5f1d036-49d7-43f4-895e-5641bbb664d5");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
