// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "1a839606-2b8a-4263-8540-782b3e66bac6");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1565188621);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1565188741);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1565198941);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1565188381);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1565188261);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1565188501);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1565188981);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1565188861);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 10791);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1565188079);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{db48630f-b68d-4b90-a60a-2881b31abb53}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1565273187430");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1565274977430");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1565198885500");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1565202485500");
user_pref("browser.search.region", "SG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190718161435");
user_pref("browser.slowStartup.averageTime", 697);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1565201641);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1565188082260");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "65cac02dbd624d239b83e839a3a989b5");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 07 Aug 2019 12:37:52 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1565188622);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190718161435");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{8f1dc5ea-8139-40ff-84f9-af9f596f2e0b}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"5.0.2\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"d3d4c661-35af-49ac-8c37-8518f70d547c\",\"fxmonitor@mozilla.org\":\"e90268cc-7064-48e5-9990-2fabdefd8491\",\"screenshots@mozilla.org\":\"aca5426c-fe37-491f-84a4-4e64a30a3d25\",\"webcompat-reporter@mozilla.org\":\"5b09c759-42b3-4729-883e-5063ebe2ed08\",\"webcompat@mozilla.org\":\"9195d613-c2fd-4f90-be2f-39fae5cd9076\",\"default-theme@mozilla.org\":\"60d18a47-b77b-4733-b3da-fd7837bb602b\",\"google@search.mozilla.org\":\"0ac5ad0e-c5fa-4d69-936e-d945a8d79852\",\"amazondotcom@search.mozilla.org\":\"306751c4-0c53-4836-9462-065d2bd16cfc\",\"bing@search.mozilla.org\":\"842b7f63-8d0d-46a9-8325-0b307d962728\",\"ddg@search.mozilla.org\":\"ebd8daf1-07b6-4afa-a726-4cb762633932\",\"ebay@search.mozilla.org\":\"08ef574c-fdcd-46c8-a123-8f64191a640c\",\"twitter@search.mozilla.org\":\"d8d2e47e-471e-4a99-b9b1-3a537736e292\",\"wikipedia@search.mozilla.org\":\"a98731b8-ce62-4705-8e1a-b346fa0fff8e\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1565188458);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1565188140);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1565188139);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("permissions.eventTelemetry.salt", "{613a9869-359e-4ef1-8d23-e7a22449f02f}");
user_pref("places.database.lastMaintenance", 1565188458);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e977619e-288e-4804-8b2e-b1b518c822e9");
user_pref("security.sandbox.plugin.tempDirSuffix", "9c6378a5-5d59-4b80-839e-2436feafbef1");
user_pref("services.blocklist.pinning.checked", 1565273308);
user_pref("services.settings.clock_skew_seconds", -226);
user_pref("services.settings.last_etag", "\"1565222410945\"");
user_pref("services.settings.last_update_seconds", 1565273308);
user_pref("services.settings.main.cfr-fxa.last_check", 1565273308);
user_pref("services.settings.main.cfr.last_check", 1565273308);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1565273308);
user_pref("services.settings.main.hijack-blocklists.last_check", 1565273308);
user_pref("services.settings.main.language-dictionaries.last_check", 1565273308);
user_pref("services.settings.main.normandy-recipes.last_check", 1565273308);
user_pref("services.settings.main.onboarding.last_check", 1565273308);
user_pref("services.settings.main.sites-classification.last_check", 1565273308);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1565273308);
user_pref("services.settings.security.onecrl.checked", 1565273308);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1565188458);
user_pref("toolkit.startup.last_success", 1565201640);
user_pref("toolkit.telemetry.cachedClientID", "8f4b18ce-2704-469a-a16c-8970acc84994");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
